language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  matrix:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis
  - mongodb

before_install:
  - ./install_memcached.sh
  - phpenv config-add .travis.php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_OPTS} --no-interaction

script:
  - vendor/bin/phpunit

after_success:
    - travis_retry php vendor/bin/php-coveralls -v
