language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis

before_install:
  - phpenv config-add .travis.php.ini

before_script:
  - composer install

script:
  - vendor/bin/phpunit

after_success:
    - travis_retry php vendor/bin/coveralls -v
