language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  matrix:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis
  - mongodb

before_install:
  - ./ci/install_dependencies.sh

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_OPTS} --no-interaction

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: Coding Standards
      php: 7.3
      install:
        - travis_retry wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
      script:
        - php php-cs-fixer -v --diff fix --config=.php_cs.dist --dry-run --no-interaction
