language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  matrix:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis
  - mongodb

before_install:
  - ./ci/install_dependencies.sh

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_OPTS} --no-interaction

script:
  - vendor/bin/phpunit
